# Generated by Django 5.2.2 on 2025-06-09 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='hora',
            field=models.TimeField(default=datetime.time(23, 1, 7, 89108)),
        ),
    ]
